version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: hotel_db
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: hotel_db
      DB_USER: root
      DB_PASS: password
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
